# Generated by Django 6.0.3 on 2026-03-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hizlisatis',
            options={'ordering': ['-tarih'], 'verbose_name': 'Satış Ürün Kalemi', 'verbose_name_plural': 'Satış Ürün Kalemleri'},
        ),
        migrations.AlterModelOptions(
            name='hizlisatisurun',
            options={'ordering': ['urun__ad'], 'verbose_name': 'Barkodlu Ürün', 'verbose_name_plural': 'Barkodlu Ürünler'},
        ),
    ]
