# Generated by Django 6.0.3 on 2026-03-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0002_alter_hizlisatis_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerjen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Alerjen Adı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Alerjen',
                'verbose_name_plural': 'Alerjenler',
                'ordering': ['ad'],
            },
        ),
        migrations.AddField(
            model_name='urun',
            name='alerjenler',
            field=models.ManyToManyField(blank=True, related_name='urunler', to='adisyon_modulu.alerjen', verbose_name='Alerjenler'),
        ),
    ]
