# Generated by Django 6.0.3 on 2026-03-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0003_alerjen_urun_alerjenler'),
    ]

    operations = [
        migrations.CreateModel(
            name='TedarikciFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(max_length=100, unique=True)),
                ('fatura_tarihi', models.DateField(blank=True, null=True)),
                ('tedarikci_adi', models.CharField(blank=True, max_length=255)),
                ('xml_dosyasi', models.FileField(upload_to='xml_faturalar/')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StokHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tipi', models.CharField(choices=[('giris', 'Giriş'), ('cikis', 'Çıkış')], max_length=10)),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=12)),
                ('birim_fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('aciklama', models.TextField(blank=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_hareketleri', to='adisyon_modulu.urun')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adisyon_modulu.tedarikcifatura')),
            ],
        ),
        migrations.CreateModel(
            name='XMLUrunEsleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_urun_adi', models.CharField(db_index=True, max_length=255)),
                ('xml_barkod', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('stok_kalemi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xml_eslesmeleri', to='adisyon_modulu.stokkalemi')),
            ],
            options={
                'verbose_name': 'XML Ürün Eşleşmesi',
                'verbose_name_plural': 'XML Ürün Eşleşmeleri',
                'unique_together': {('xml_urun_adi', 'xml_barkod')},
            },
        ),
    ]
