# Generated by Django 6.0.3 on 2026-03-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0004_tedarikcifatura_stokhareketi_xmlurunesleme'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokkalemi',
            name='otomatik_urun_olustur',
            field=models.BooleanField(default=False, verbose_name='Otomatik ürün oluştur'),
        ),
        migrations.AddField(
            model_name='stokkalemi',
            name='satilabilir_mi',
            field=models.BooleanField(default=False, verbose_name='Direkt satılabilir mi?'),
        ),
        migrations.AddField(
            model_name='stokkalemi',
            name='uretimde_kullanilir_mi',
            field=models.BooleanField(default=True, verbose_name='Üretimde kullanılır mı?'),
        ),
    ]
