# Generated by Django 6.0.3 on 2026-03-25 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0005_stokkalemi_otomatik_urun_olustur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='stok_kalemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urunler', to='adisyon_modulu.stokkalemi', verbose_name='Bağlı Stok Kalemi'),
        ),
    ]
