# Generated by Django 6.0.3 on 2026-03-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0006_urun_stok_kalemi'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='receteli_mi',
            field=models.BooleanField(default=False, verbose_name='Reçeteli ürün mü?'),
        ),
    ]
