# Generated by Django 6.0.3 on 2026-03-25 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0007_urun_receteli_mi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UretimFis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Üretim Miktarı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adisyon_modulu.sube', verbose_name='Şube')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adisyon_modulu.urun', verbose_name='Ürün')),
            ],
        ),
    ]
