# Generated by Django 6.0.3 on 2026-03-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0008_uretimfis'),
    ]

    operations = [
        migrations.AddField(
            model_name='garsoncagri',
            name='tamamlandi_mi',
            field=models.BooleanField(default=False),
        ),
    ]
