# Generated by Django 6.0.3 on 2026-03-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0009_garsoncagri_tamamlandi_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='sira',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
    ]
