# Generated by Django 6.0.3 on 2026-03-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0010_urun_sira'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urun',
            options={'ordering': ['sira', 'ad'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
    ]
