# Generated by Django 6.0.3 on 2026-04-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0011_alter_urun_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisitem',
            name='eklenme_zamani',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Sipariş Verilme Zamanı'),
        ),
        migrations.AddField(
            model_name='siparisitem',
            name='hazir_olma_zamani',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hazır İşaretlenme Zamanı'),
        ),
    ]
