# Generated by Django 6.0.3 on 2026-04-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0012_siparisitem_eklenme_zamani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masa',
            name='genislik',
            field=models.FloatField(default=120, help_text='Masa Genişliği'),
        ),
        migrations.AddField(
            model_name='masa',
            name='pos_x',
            field=models.FloatField(default=0, help_text='X Koordinatı'),
        ),
        migrations.AddField(
            model_name='masa',
            name='pos_y',
            field=models.FloatField(default=0, help_text='Y Koordinatı'),
        ),
        migrations.AddField(
            model_name='masa',
            name='yukseklik',
            field=models.FloatField(default=120, help_text='Masa Yüksekliği'),
        ),
        migrations.AddField(
            model_name='sube',
            name='masa_plani_genislik',
            field=models.IntegerField(default=1200, verbose_name='Masa Planı Genişliği'),
        ),
        migrations.AddField(
            model_name='sube',
            name='masa_plani_yukseklik',
            field=models.IntegerField(default=800, verbose_name='Masa Planı Yüksekliği'),
        ),
    ]
