# Generated by Django 6.0.3 on 2026-04-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adisyon_modulu', '0013_masa_genislik_masa_pos_x_masa_pos_y_masa_yukseklik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sube',
            name='kroki_arkaplan',
            field=models.ImageField(blank=True, null=True, upload_to='krokiler/', verbose_name='Kroki Arka Planı'),
        ),
        migrations.AddField(
            model_name='yedeklemeayarlari',
            name='yedekleme_saati',
            field=models.TimeField(default='03:00', verbose_name='Yedekleme Saati'),
        ),
    ]
